[pytest]
addopts = -p no:cacheprovider
norecursedirs = pytest-cache-files-*
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning
