from enum import Enum


class ErrorCode(str, Enum):
    """错误码枚举（集中管理）。"""

    VALIDATION_FAILED = "VALIDATION_FAILED"
    KB_NOT_FOUND = "KB_NOT_FOUND"
    KB_ALREADY_EXISTS = "KB_ALREADY_EXISTS"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    INGEST_JOB_NOT_FOUND = "INGEST_JOB_NOT_FOUND"
    INGEST_JOB_NOT_RETRYABLE = "INGEST_JOB_NOT_RETRYABLE"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    INGEST_PARSE_FAILED = "INGEST_PARSE_FAILED"
    INGEST_CHUNK_FAILED = "INGEST_CHUNK_FAILED"
    INGEST_EMBED_FAILED = "INGEST_EMBED_FAILED"
    INGEST_CANCELED = "INGEST_CANCELED"
    INGEST_QUEUE_UNAVAILABLE = "INGEST_QUEUE_UNAVAILABLE"
    INGEST_WORKER_FAILED = "INGEST_WORKER_FAILED"
    VECTOR_UPSERT_FAILED = "VECTOR_UPSERT_FAILED"
    VECTOR_SEARCH_FAILED = "VECTOR_SEARCH_FAILED"
    RAG_CONTEXT_BUILD_FAILED = "RAG_CONTEXT_BUILD_FAILED"
    RAG_MODEL_FAILED = "RAG_MODEL_FAILED"
    RAG_NO_EVIDENCE = "RAG_NO_EVIDENCE"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
